version: "3"
services: 
  app:
    container_name: NODE_WEBSERVER
    hostname: webserver
    environment: 
      #defines environment variables for the app
      - MONGO_DB=mongodb://db:27017/schoologydb
      - REDIS_URL=redis://redis:6379
      - HOSTNAME=webserver
    build: .
    ports:
      - "3000:3000"
    command: yarn start
    depends_on: 
      - db
      - redis
    links:
      - db
      - redis
  db:
    image: 'mongo'
    container_name: SCHOOLOGY_DB
    ports: 
      - '27017:27017'
    volumes:
      - ./data/db:/data/db
  redis:
    container_name: SCHOOLOGY_REDIS
    image: "redis"
    ports:
      - '6379:6379'